=== smukherj1/csc343/assignment3/music.dtd
<!ELEMENT music (songs, playlists)>
<!ELEMENT songs (song+)>
<!ELEMENT song (title, artist, composers, album?)>
<!ATTLIST song
    sid ID #REQUIRED
    time CDATA #REQUIRED
    year CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT composers (composer+)>
<!ELEMENT composer (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT playlists (playlist+)>
<!ATTLIST playlist
    pid ID #REQUIRED
    creator CDATA #IMPLIED>
<!ELEMENT playlist (track+)>
<!ELEMENT track EMPTY>
<!ATTLIST track sid IDREF #REQUIRED>

=== smukherj1/csc343/assignment3/music.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE music SYSTEM "music.dtd">
<music>
<songs>
<song sid="s0" time="23" year="2010">
<title>Song 0</title>
<artist>Artist 76</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
</song><song sid="s1" time="23" year="1998">
<title>Song 1</title>
<artist>Artist 40</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
</composers>
</song><song sid="s2" time="23" year="1997">
<title>Song 2</title>
<artist>Artist 58</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
<composer>Composer 4</composer>
</composers>
<album>Album 28</album>
</song><song sid="s3" time="23" year="2007">
<title>Song 3</title>
<artist>Artist 62</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
</composers>
<album>Album 99</album>
</song><song sid="s4" time="23" year="2009">
<title>Song 4</title>
<artist>Artist 91</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
</composers>
<album>Album 90</album>
</song><song sid="s5" time="23" year="2004">
<title>Song 5</title>
<artist>Artist 47</artist>
<composers>
<composer>Composer 0</composer>
</composers>
</song><song sid="s6" time="23" year="2001">
<title>Song 6</title>
<artist>Artist 92</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
<composer>Composer 4</composer>
</composers>
</song><song sid="s7" time="23" year="2011">
<title>Song 7</title>
<artist>Artist 26</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
<composer>Composer 4</composer>
</composers>
<album>Album 1</album>
</song><song sid="s8" time="23" year="2005">
<title>Song 8</title>
<artist>Artist 40</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
<composer>Composer 4</composer>
</composers>
<album>Album 0</album>
</song><song sid="s9" time="23" year="1997">
<title>Song 9</title>
<artist>Artist 87</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
</composers>
</song><song sid="s10" time="23" year="2011">
<title>Song 10</title>
<artist>Artist 19</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
</song><song sid="s11" time="23" year="2014">
<title>Song 11</title>
<artist>Artist 81</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
</song><song sid="s12" time="23" year="1991">
<title>Song 12</title>
<artist>Artist 51</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
<composer>Composer 4</composer>
</composers>
</song><song sid="s13" time="23" year="1999">
<title>Song 13</title>
<artist>Artist 71</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
<album>Album 54</album>
</song><song sid="s14" time="23" year="2014">
<title>Song 14</title>
<artist>Artist 60</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
</song><song sid="s15" time="23" year="2001">
<title>Song 15</title>
<artist>Artist 38</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
</song><song sid="s16" time="23" year="1986">
<title>Song 16</title>
<artist>Artist 18</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
</composers>
<album>Album 48</album>
</song><song sid="s17" time="23" year="1983">
<title>Song 17</title>
<artist>Artist 76</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
<composer>Composer 4</composer>
</composers>
<album>Album 85</album>
</song><song sid="s18" time="23" year="2012">
<title>Song 18</title>
<artist>Artist 93</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
</song><song sid="s19" time="23" year="2005">
<title>Song 19</title>
<artist>Artist 27</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
<composer>Composer 4</composer>
</composers>
<album>Album 90</album>
</song><song sid="s20" time="23" year="2001">
<title>Song 20</title>
<artist>Artist 95</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
</song><song sid="s21" time="23" year="2003">
<title>Song 21</title>
<artist>Artist 100</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
<composer>Composer 4</composer>
</composers>
<album>Album 8</album>
</song><song sid="s22" time="23" year="2002">
<title>Song 22</title>
<artist>Artist 49</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
</composers>
<album>Album 24</album>
</song><song sid="s23" time="23" year="2006">
<title>Song 23</title>
<artist>Artist 11</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
</composers>
<album>Album 33</album>
</song><song sid="s24" time="23" year="2009">
<title>Song 24</title>
<artist>Artist 10</artist>
<composers>
<composer>Composer 0</composer>
</composers>
<album>Album 4</album>
</song><song sid="s25" time="23" year="2000">
<title>Song 25</title>
<artist>Artist 91</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
<album>Album 2</album>
</song><song sid="s26" time="23" year="2002">
<title>Song 26</title>
<artist>Artist 61</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
</song><song sid="s27" time="23" year="1993">
<title>Song 27</title>
<artist>Artist 99</artist>
<composers>
<composer>Composer 0</composer>
</composers>
</song><song sid="s28" time="23" year="2014">
<title>Song 28</title>
<artist>Artist 18</artist>
<composers>
<composer>Composer 0</composer>
</composers>
</song><song sid="s29" time="23" year="2008">
<title>Song 29</title>
<artist>Artist 94</artist>
<composers>
<composer>Composer 0</composer>
</composers>
</song><song sid="s30" time="23" year="1983">
<title>Song 30</title>
<artist>Artist 26</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
</composers>
<album>Album 35</album>
</song><song sid="s31" time="23" year="1986">
<title>Song 31</title>
<artist>Artist 50</artist>
<composers>
<composer>Composer 0</composer>
</composers>
</song><song sid="s32" time="23" year="2015">
<title>Song 32</title>
<artist>Artist 20</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
</composers>
<album>Album 84</album>
</song><song sid="s33" time="23" year="2013">
<title>Song 33</title>
<artist>Artist 17</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
</composers>
<album>Album 5</album>
</song><song sid="s34" time="23" year="2004">
<title>Song 34</title>
<artist>Artist 85</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
</composers>
</song><song sid="s35" time="23" year="2001">
<title>Song 35</title>
<artist>Artist 44</artist>
<composers>
<composer>Composer 0</composer>
</composers>
</song><song sid="s36" time="23" year="1994">
<title>Song 36</title>
<artist>Artist 57</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
</song><song sid="s37" time="23" year="1992">
<title>Song 37</title>
<artist>Artist 84</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
</composers>
<album>Album 1</album>
</song><song sid="s38" time="23" year="2006">
<title>Song 38</title>
<artist>Artist 33</artist>
<composers>
<composer>Composer 0</composer>
</composers>
</song><song sid="s39" time="23" year="1988">
<title>Song 39</title>
<artist>Artist 96</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
</composers>
</song><song sid="s40" time="23" year="1992">
<title>Song 40</title>
<artist>Artist 95</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
</composers>
<album>Album 72</album>
</song><song sid="s41" time="23" year="1993">
<title>Song 41</title>
<artist>Artist 41</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
<composer>Composer 3</composer>
</composers>
</song><song sid="s42" time="23" year="1986">
<title>Song 42</title>
<artist>Artist 33</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
</composers>
<album>Album 38</album>
</song><song sid="s43" time="23" year="2011">
<title>Song 43</title>
<artist>Artist 57</artist>
<composers>
<composer>Composer 0</composer>
<composer>Composer 1</composer>
<composer>Composer 2</composer>
</composers>
